In [2]:
pip install pandas

WARNING: The directory '/Users/atewari/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Collecting pandas
  Downloading pandas-2.2.3-cp312-cp312-macosx_10_9_x86_64.whl.metadata (89 kB)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/Cellar/jupyterlab/4.2.5_1/libexec/lib/python3.12/site-packages (from pandas) (2.2.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/Cellar/jupyterlab/4.2.5_1/libexec/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /usr/local/Cellar/jupyterlab/4.2.5_1/libexec/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.2.3-cp312-cp312-macosx_10_9_x86_64.whl (12.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.5/12.5 MB 1.3 MB/s eta 0:00:0000:0100:01m
Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
Downloading tzdata-2025.1-py2.py3-none-any.whl (346 kB)
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.2.3 pytz-2024.2 tzdata-2025.1

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: /usr/local/Cellar/jupyterlab/4.2.5_1/libexec/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [52]:
import pandas as pd

In [53]:
pd.read_csv("global_warming_dataset.csv")

,Country,Year,Temperature_Anomaly,CO2_Emissions,Population,Forest_Area,GDP,Renewable_Energy_Usage,Methane_Emissions,Sea_Level_Rise,...,Waste_Management,Per_Capita_Emissions,Industrial_Activity,Air_Pollution_Index,Biodiversity_Index,Ocean_Acidification,Fossil_Fuel_Usage,Energy_Consumption_Per_Capita,Policy_Score,Average_Temperature
0,Country_93,2014,0.444954,4.579080e+08,4.926732e+08,72.295357,5.192677e+12,36.725699,1.056885e+06,20.953840,...,94.982931,12.039703,83.804880,216.911429,86.936256,7.647408,61.548382,706.918809,37.671300,15.014084
1,Country_15,2020,-1.171616,5.049503e+08,1.252169e+09,17.259684,8.252128e+12,77.547901,1.986813e+06,45.599595,...,62.064250,2.853957,47.014265,35.869182,44.904331,7.569353,82.423750,2616.238324,86.581725,-1.277086
2,Country_88,2014,0.560926,8.174279e+08,8.715338e+08,43.012490,7.029643e+12,80.280808,7.876279e+06,10.131856,...,8.455126,17.839710,85.148984,105.028858,79.836502,8.381296,64.220171,2645.886297,95.913832,9.651690
3,Country_161,2018,-1.776189,7.225106e+08,1.153826e+09,70.795607,3.439063e+12,16.768676,4.461995e+05,10.515054,...,68.040178,15.705066,85.176157,277.908140,51.474668,8.471651,57.044926,1280.092447,4.256841,19.043270
4,Country_58,2019,0.655015,5.151287e+08,8.878241e+08,14.319157,8.393075e+12,57.052025,5.237285e+06,21.974672,...,33.577333,17.666408,37.448116,252.668321,14.452447,7.627174,93.458955,780.826524,96.654733,30.222646
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8745,Country_191,2022,-1.493139,6.243718e+08,1.238373e+09,73.189076,8.085692e+11,25.043953,1.747628e+04,42.887488,...,0.301647,13.253131,19.418004,214.600196,22.822924,7.749058,71.460504,4269.126875,14.195119,39.089372
8746,Country_20,2021,-1.785858,6.532305e+08,1.049440e+09,17.385819,8.281341e+12,7.593129,1.810332e+06,8.534359,...,36.460917,11.228915,62.417570,28.838847,60.112392,7.519493,99.174586,1389.749698,97.231873,4.991187
8747,Country_158,2013,1.488299,2.076319e+08,4.279195e+08,50.420395,8.815064e+12,29.356100,7.818084e+06,22.102856,...,96.665567,9.174712,72.030293,285.254171,26.543208,7.914015,14.260289,3256.359943,64.412785,33.905508
8748,Country_107,2014,-1.776688,6.128349e+08,8.019814e+08,93.674734,3.271392e+12,55.004906,2.604094e+06,30.154030,...,79.894742,3.482068,39.322685,36.672130,36.277971,7.929089,77.022538,880.629609,40.684711,32.148320
8749,Country_69,2018,-1.400119,8.156151e+08,1.476783e+09,30.684558,5.612048e+12,82.181155,9.694484e+06,35.329960,...,65.834145,12.558290,66.831098,38.104126,1.368974,7.628241,99.994866,1152.969690,34.845420,27.083474

In [54]:
df = pd.read_csv("global_warming_dataset.csv")

In [68]:
year_filter = df['Year'] >= 2020

In [69]:
df1 = df[year_filter]

In [76]:
columns = ['Country', 'Year', 'CO2_Emissions', 'Population', 'Forest_Area', 'GDP', 'Renewable_Energy_Usage', 'Sea_Level_Rise', 'Per_Capita_Emissions', 'Fossil_Fuel_Usage']

In [77]:
df1[columns].to_csv('data.csv', index=False)

In [78]:
df1_desc = df1[columns].describe()

In [79]:
df1_desc

,Year,CO2_Emissions,Population,Forest_Area,GDP,Renewable_Energy_Usage,Sea_Level_Rise,Per_Capita_Emissions,Fossil_Fuel_Usage
count,3106.000000,3.106000e+03,3.106000e+03,3106.000000,3.106000e+03,3106.000000,3106.000000,3106.000000,3106.000000
mean,2021.478107,5.003586e+08,7.463359e+08,51.432038,4.986892e+12,51.050592,22.779280,10.125480,50.136525
std,1.110775,2.845867e+08,4.338750e+08,28.505584,2.882581e+12,28.656418,15.775171,5.783194,28.848283
min,2020.000000,7.107863e+05,1.280287e+06,0.035802,1.524737e+08,0.019199,-4.994242,0.000471,0.010804
25%,2020.250000,2.597854e+08,3.662079e+08,27.206298,2.491796e+12,26.920120,9.180155,5.138036,25.556319
50%,2021.000000,4.986744e+08,7.395169e+08,52.395491,4.920039e+12,51.814551,22.716748,10.165469,50.448769
75%,2022.000000,7.443226e+08,1.116762e+09,75.659880,7.456137e+12,76.397327,36.376616,15.236608,74.757158
max,2023.000000,9.998894e+08,1.499200e+09,99.914539,9.993365e+12,99.998458,49.992391,19.999033,99.940127

In [49]:
df1_desc.to_csv('global_warming_dataset_desc.csv', index=False)